# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Galico Home Comfort
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://galicogas.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Galico Home Comfort Inc.
address_line: Almonte, Ontario
telephone_number: (343) 464-2219
company_email: hello@galico.ca
google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3618.727010735933!2d91.837871!3d24.907291700000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1404919738144

# Social Link
facebook_link: http://www.facebook.com/galicogas

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
 - _data
 - _includes
 - _layouts
 - _service-area
 - _heating
 - _hot-water
 - _gasfitting
 - _plumbing
  
exclude:
 - node_modules
 - package.json
 
# SEO settings
defaults:
  - scope:
      path: "_hot-water"
      type: hot-water
    values:
      meta_description: "Professional hot water system installation, repair, and maintenance services in Ontario. Reliable and efficient solutions for your home or business."
      og_type: "article"
      og_section: "Hot Water Systems"
  
  - scope:
      path: "_gasfitting"
      type: gasfitting
    values:
      meta_description: "Licensed gasfitting services including gas line installation, appliance hookup, and leak detection. Certified technicians serving the Ottawa and West of Ottawa."
      og_type: "article"
      og_section: "Gasfitting"
  
  - scope:
      path: "_heating"
      type: heating
    values:
      meta_description: "Expert heating system installation services. Hydronic heating, furnaces, and radiant floor heating solutions for maximum comfort."
      og_type: "article"
      og_section: "Heating Services"